print("Hello World")
print ("Ansar")
print ("Ansar Ahmad")
print ("Hi,I am Python.")
print ("25")
print ("2*2")
print ("2","+","5","+","9")
print ("2","+","2","+","9")
print ("Hello,","I","am","Ansar")
print ("Ansar","is","20","years","old")
print ("Hello Ansar,"+"How are you?")
print ("I am 20 years old"+"and"+"My freind is 21 years old.")
print ("20" + "+" + "2" + "=" + "22")
print ("My brother is " + "25" + "years old.")
